#!/bin/sh
#
# /etc/init.d/PLCupdater
# Subsystem file for "PLCupdater" service
### BEGIN INIT INFO
# Provides:          PLCupdater
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       PLCupdater
### END INIT INFO
PIDFILE=/var/run/PLCupdater.pid
RETVAL=0
prog="PLCupdater"

start() {
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE ); then
        echo "Service already running" >&2
        return 1
    fi
    echo -n "Starting service" >&2
    su -c "start-stop-daemon -SbmCv -x /usr/bin/nohup -p \"$PIDFILE\" -- /usr/local/bin/mono /home/pi/PLCupdater/PLCupdater.exe"
    echo 'Service started' >&2
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
    echo 'Stopping service...' >&2
    start-stop-daemon -K -p "$PIDFILE"
    rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
exit
